# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

references:

  workspace_root: &workspace_root
    ~/repo

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
      
  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

  restore_yarn_cache: &restore_yarn_cache
    restore_cache: 
      keys:
        - v2-yarn-cache-{{ checksum "yarn.lock" }}-{{ arch }}-{{ .Environment.CACHE_VERSION }}

  save_yarn_cache: &save_yarn_cache
    save_cache: 
      key: v2-yarn-cache-{{ checksum "yarn.lock" }}-{{ arch }}-{{ .Environment.CACHE_VERSION }}
      paths:
        - ~/.cache/yarn
        - node_modules
        - .tools

  yarn_install: &yarn_install
    name: Installing
    command: |
      echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      yarn global add lerna
      yarn install --frozen-lockfile --ignore-optional

  tools_install: &tools_install
    name: Installing tools
    command: |
      mkdir -p .tools/
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./.tools/cc-test-reporter
      chmod +x ./.tools/cc-test-reporter

executors:
  node:
    docker:
      - image: circleci/node:14
    working_directory: *workspace_root
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Berlin"

jobs:

  lint_test_build:
    executor: node
    steps:
      # Install dependencies
#       - *restore_repo
      - checkout
      - *restore_yarn_cache
      - run: *yarn_install
      - run: *tools_install
      - *save_yarn_cache
      # Lint, Test & Build
      - run:
          command: yarn lint
      - run:
          command: yarn test
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      # Codeclimate codecoverage reporting
      - run:
          command: yarn publish-report
      - store_test_results:
          path: ./reports/junit
      - store_artifacts:
          path: ./reports/junit
      - store_artifacts:
          path: ./coverage
      - run: 
          command: yarn build
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./packages/*/dist
            
  publish_pkg:
    executor: node
    steps:
      - checkout
      - *restore_yarn_cache
      - *attach_workspace
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: git config --global user.email "01@01alchemist.com"
      - run: git config --global user.name "Nidin Vinayakan"
      - run: yarn global add lerna
      - run: yarn run publish
      
workflows:
  version: 2

  default:
    jobs:
      - lint_test_build
      - publish_pkg:
          requires:
            - lint_test_build
