# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

workflows:
  version: 2
  default:
    jobs:
      - lint_test_build_publish:
          context: GITHUB

references:
  workspace_root: &workspace_root ~/repo

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

  restore_npm_cache: &restore_npm_cache
    restore_cache:
      keys:
        - v1-npm-cache-{{ checksum "package-lock.json" }}-{{ arch }}-{{
          .Environment.CACHE_VERSION }}

  save_npm_cache: &save_npm_cache
    save_cache:
      key:
        v1-npm-cache-{{ checksum "package-lock.json" }}-{{ arch }}-{{
        .Environment.CACHE_VERSION }}
      paths:
        - ~/.npm
        - node_modules
        - .tools

  npm_install: &npm_install
    name: Installing
    command: |
      echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      npm install

  tools_install: &tools_install
    name: Installing tools
    command: |
      mkdir -p .tools/
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./.tools/cc-test-reporter
      chmod +x ./.tools/cc-test-reporter

executors:
  node:
    docker:
      - image: cimg/node:18.19.0
    working_directory: *workspace_root
    environment:
      TZ: '/usr/share/zoneinfo/Europe/Berlin'

jobs:
  lint_test_build_publish:
    executor: node
    steps:
      # Install dependencies
      #       - *restore_repo
      - checkout
      - *restore_npm_cache
      - run: *npm_install
      - run: *tools_install
      - *save_npm_cache
      # Lint, Test & Build
      - run:
          command: npm run lint
      - run:
          command: npm run test
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'
            GH_TOKEN: $GITHUB_TOKEN
      # Codeclimate codecoverage reporting
      - run:
          command: npm run publish-report
      - store_test_results:
          path: ./reports/junit
      - store_artifacts:
          path: ./reports/junit
      - store_artifacts:
          path: ./coverage
      - run:
          command: npm run build
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./packages/*/dist
      - run: git config --global user.email "01@01alchemist.com"
      - run: git config --global user.name "Nidin Vinayakan"
      - run: npm run publish
